### PR TITLE
common-instancetypes: Wait until SSP is deployed during URI test

### LINKED ISSUE #692: common-instancetypes URL func test not waiting for SSP to be deployed
/kind bug

**What happened**:

$subject

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kubevirt_ssp-operator/641/pull-ci-kubevirt-ssp-operator-main-e2e-single-node-functests/1708832445794619392

```
Common Instance Types operand should reconcile from URL when provided
/go/src/github.com/kubevirt/ssp-operator/tests/common_instancetypes_test.go:39
  [FAILED] in [It] - /go/src/github.com/kubevirt/ssp-operator/tests/common_instancetypes_test.go:58 @ 10/02/23 14:35:24.42
• [FAILED] [6.819 seconds]
Common Instance Types operand [It] should reconcile from URL when provided
/go/src/github.com/kubevirt/ssp-operator/tests/common_instancetypes_test.go:39
  [FAILED] Expected success, but got an error:
      <*errors.StatusError | 0xc0018d48c0>: 
      virtualmachineclusterpreferences.instancetype.kubevirt.io "centos.9.stream.desktop" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "virtualmachineclusterpreferences.instancetype.kubevirt.io \"centos.9.stream.desktop\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "centos.9.stream.desktop",
                  Group: "instancetype.kubevirt.io",
                  Kind: "virtualmachineclusterpreferences",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
  In [It] at: /go/src/github.com/kubevirt/ssp-operator/tests/common_instancetypes_test.go:58 @ 10/02/23 14:35:24.42
```

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt_ssp-operator/641/pull-ci-kubevirt-ssp-operator-main-e2e-single-node-functests/1708832445794619392/artifacts/e2e-single-node-functests/gather-extra/artifacts/pods/kubevirt_ssp-operator-5f6fd4fd54-6xxgf_manager.log

```
{"level":"info","ts":"2023-10-02T14:35:21Z","logger":"controllers.SSP","msg":"Reconciling common-instancetypes from URL https://github.com/kubevirt/common-instancetypes//VirtualMachineClusterPreferences?ref=v0.1.0","ssp":{"Name":"test-ssp","Namespace":"ssp-operator-functests"}}
[..]
{"level":"info","ts":"2023-10-02T14:35:24Z","logger":"controllers.SSP","msg":"Updated VirtualMachineClusterPreference resource: cirros","ssp":{"Name":"test-ssp","Namespace":"ssp-operator-functests"}}
{"level":"info","ts":"2023-10-02T14:35:24Z","logger":"controllers.SSP","msg":"Updated VirtualMachineClusterPreference resource: alpine","ssp":{"Name":"test-ssp","Namespace":"ssp-operator-functests"}}
{"level":"info","ts":"2023-10-02T14:35:24Z","logger":"controllers.SSP","msg":"Reconciliation event received","ssp":{"Name":"test-ssp","Namespace":"ssp-operator-functests"},"cause_type":"VirtualMachineClusterPreference","cause_object":"/alpine"}
{"level":"info","ts":"2023-10-02T14:35:24Z","logger":"controllers.SSP","msg":"Reconciliation event received","ssp":{"Name":"test-ssp","Namespace":"ssp-operator-functests"},"cause_type":"VirtualMachineClusterPreference","cause_object":"/alpine"}
[..]
{"level":"info","ts":"2023-10-02T14:35:25Z","logger":"controllers.SSP","msg":"Starting reconciliation","ssp":{"Name":"test-ssp","Namespace":"ssp-operator-functests"}}
{"level":"info","ts":"2023-10-02T14:35:25Z","logger":"controllers.SSP","msg":"Reconciling operands...","ssp":{"Name":"test-ssp","Namespace":"ssp-operator-functests"}}
{"level":"info","ts":"2023-10-02T14:35:25Z","logger":"controllers.SSP","msg":"Reconciling common-instancetypes from internal bundle","ssp":{"Name":"test-ssp","Namespace":"ssp-operator-functests"}}
```

**What you expected to happen**:

The test shouldn't race the reconcile loop and should wait until SSP is deployed.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- SSP Operator version:
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by lyarwood**
/cc @codingben 
/cc @0xFelix 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**: 

Fixes #692 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: tests/common_instancetypes_test.go [hunk 1]
```diff
@@ -37,12 +37,14 @@ var _ = Describe("Common Instance Types", func() {
 			}
 		})
 		It("should reconcile from URL when provided", func() {
-			URL := "https://github.com/kubevirt/common-instancetypes//VirtualMachineClusterPreferences?ref=v0.1.0"
+			URL := "https://github.com/kubevirt/common-instancetypes//VirtualMachineClusterPreferences?ref=v0.3.3"
```
Comment (codingben) [inline tests/common_instancetypes_test.go:40]: I know isn't a good practice to set main branches as a reference, but can we do it? instead of bumping this tag. @0xFelix What did you mean when you said the URL is wrong, did you mean to the ref version?

Comment (lyarwood) [reply tests/common_instancetypes_test.go:40]: No, this isn't set to `main` as we'd then need another change each time a release branch is cut pinning said branch to a known supported release of common-instancetypes by SSP and the underlying KubeVirt version we support.

This is all being deprecated in `v0.19.0` FWIW so I wouldn't get too invested in this.

Comment (codingben) [reply tests/common_instancetypes_test.go:40]: Ack, thanks.

**Comment by lyarwood** [comment]
/cc @akrejcir 
/cc @ksimon1 

Would either of you mind taking a look at this while Felix is out today?

**Review by 0xFelix — APPROVED** [review]
/approve

Looks good, thanks!

File: tests/common_instancetypes_test.go (hunk 1 above)
Comment (0xFelix) [reply tests/common_instancetypes_test.go:40]: I meant the URL is only referring to `VirtualMachineClusterPreferences`, but not `VirtualMachineClusterInstancetypes`, while below we also test that all expected got deployed `VirtualMachineClusterInstancetypes` (although 0 of 0 is also a correct assertion).
